### ISSUE TITLE
Where and How to use this library

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/java-tracerresolver#15]
There are two places where this library can be used -- instrumentions and tracerresolver impl for a specific tracer.

Instrumentations can consume tracer instance directly, via `GlobalTracer`, via CDI... or Tracerresolver.
Usually Opentracing instrumentations can be used together (e.g. java-jaxrs and java-jdbc). All these instrumentations can implement a fall-back mechanism for getting the tracer 1.directly 2. GlobalTracer.. N. Tracerresolver. 

I have seen patterns where instrumentation sets `GlobalTracer` with resolved tracer. I guess this might cause some issues: 
GlobalTracer might thrown an exception when registering two different tracers. So when there are two tracers on classpath you might get an exception or not depending on ServiceLoader.load order (if it is not deterministic).

It is a little bit inconvenient to implement this mechanism in all different instrumentations. Therefore I propose that tracerresolver impls (https://github.com/uber/jaeger-client-java/tree/master/jaeger-tracerresolver) would set tracer to `GlobalTracer`. If we go with this approach and there are two traceresolvers impls on classpath we get always an exception (deterministic).

Related discussions:
* https://github.com/opentracing-contrib/java-spring-cloud/pull/16
* https://github.com/opentracing-contrib/java-cdi/pull/1#discussion_r131088217

cc @jpkrohling @objectiser

**Comment by sjoerdtalsma** [comment]
There might be a simpler solution that doesn't require any change in resolved tracers: if we agree on this order (1.explicit, 2.global, ...resolve) the TracerResolver could simply always return the GlobalTracer (if registered) and not even attempt resolving on its own.

**Comment by sjoerdtalsma** [comment]
By the way; I think having two tracers on the classpath should **not** result in an exception.
If they have different `@Priority` annotations the appropriate will get chosen.

If there must be disambiguity in case of two equivalent priority tracers, I'd argue logging a warning and returning the NoopTracer may be best.
Most software I encounter should run even if tracing doesn't work. It shouldn't go unnoticed (hence logging a warning) but the 'main code' should always keep working even if tracing got messed up somehow (in this case likely by adding a competing tracer library).

**Comment by jpkrohling** [comment]
Random thoughts:

- Integration/instrumentation (JAX-RS, EJB, JDBC, ...) code should get a Tracer via GlobalTracer by _default_. It might, of course, provide mechanisms for specifying a tracer (in a constructor, for instance), but that should not be the default nor the recommended procedure.
- The target application is responsible for making the bridge between GlobalTracer and TracerResolver, perhaps by using the outcome of TracerResolver to set a GlobalTracer. We cannot expect, for example, the JAX-RS, EJB or JDBC integration to set a GlobalTracer with the outcome of the TracerResolver.
- Components that bring value in making this bridge, like the CDI and Spring integration, are "exempted" from the previous rule. For instance, an application might simply expose a `@Produces Tracer tracer` (+ whatever is necessary to get it selected by the framework) and get it used by all instrumentation libraries. The CDI/Spring library then sets the GlobalTracer to use this produced tracer. For the other instrumentation libraries (JAX-RS, ...), it's transparent how this tracer was set.
- Every component that attempts to make this bridge should provide a flag to turn off this logic (like the `skipTracerInitializer` from the CDI PR)

> So when there are two tracers on classpath you might get an exception or not depending on ServiceLoader.load order (if it is not deterministic).

I'm with @sjoerdtalsma on this one: there should be *no* exceptions. Based on the rules above, the target application is ultimately responsible for setting a tracer to the GlobalTracer, perhaps using the service loader. If the service loader yields more tracers, it's the target application's responsibility to disambiguate it. The Tracer Resolver and/or the CDI/Spring integration might simply skip the selection logic (and warn on the logs) if it's not clear which Tracer should be resolved/produced.

**Comment by objectiser** [comment]
@jpkrohling Agree with your points - but could you clarify the reason for

> Every component that attempts to make this bridge should provide a flag to turn off this logic (like the skipTracerInitializer from the CDI PR)

**Comment by jpkrohling** [comment]
Sure: this "bridge" is made on some assumptions, probably valid for the most common scenarios, but we can't anticipate all the use cases. There might be a need for some applications to completely disable this bridge code, but keep the other parts of the integration.

Concrete example: the application itself might use the Service Loader to check for concrete tracers in the classpath and use their own logic to pick which one to use and register it with the Global Tracer.

**Comment by objectiser** [comment]
Not sure about this usecase  - in this case I don't think they would use the tracerresolver provided by their chosen tracer, but instead just instantiate it directly in code.

**Comment by jpkrohling** [comment]
Exactly :-) Considering that this "bridge" code is within the CDI or Spring libraries, it would mean to skip the `TracerResolver` integration.

**Comment by pavolloffay** [comment]
I mostly agree with @jpkrohling's points https://github.com/opentracing-contrib/java-tracerresolver/issues/15#issuecomment-320206657 except the third "exempted" and fourth use-case. It might be very inconvenient to configure multiple `skipTracerInitializer`-like properties from different yet independent instrumentations. Also @objectiser mentioned:

> Not sure about this usecase - in this case I don't think they would use the tracerresolver provided by their chosen tracer, but instead just instantiate it directly in code.

I still think that we should go with route when tracerresolver-impls (eg `jaeger-tracerresolver`) would set resolved tracer to `GlobalTracer`. It would simplify a lot of things. 

Some reasons why to not use tracerresolver directly in instrumentations and rather use proposed approach:
* All instrumentations support `GlobalTracer` for use-cases when tracer is not explicitly specified. (there are minimum instrumentations which support tracerresolver)
* If instrumentation does not support tracerrresolver you are done, you cannot use "no code change" approach.
* tracerresolver has not been widely adopted. Currently only Jaeger supports it.
* why to make bindings to tracerresolver in every instrumentation if it can be done once in tracerresolver impl?

**Comment by pavolloffay** [comment]
cc @yurishkuro

**Comment by sjoerdtalsma** [comment]
> I still think that we should go with route when tracerresolver-impls (eg jaeger-tracerresolver) would set resolved tracer to GlobalTracer. It would simplify a lot of things.

If we make this a general 'rule', why not add it in the `TracerResolver` class itself?
I actually think there's merit to your idea; there should in general be only one 'implicit global' tracer per application. If it's already set as 'the' GlobalTracer, I don't see a point in trying to resolve one.

My only objection to your idea was how to handle conflicting resolutions which I'm willing to discuss in a different issue, as I think it in fact is another issue from your main point.

**Comment by pavolloffay** [comment]
This might be also interesting for others @tedsuo @bhs @wu-sheng (if you use tracerresolver or plan to do so)

**Comment by sjoerdtalsma** [comment]
I created a PR #16 to tinker with the idea to always let the `GlobalTracer` 'win' any resolution if it is already registered. Please leave review comments if you like or dislike this idea.

**Comment by objectiser** [comment]
> why to make bindings to tracerresolver in every instrumentation if it can be done once in tracerresolver impl?

@pavolloffay Not sure where this came from - there is no binding to tracerresolver in any instrumention. The use of the tracerresolver is simply to obtain the Tracer once per app invocation, so providing runtime specific support (e.g. a SB Bean autoconfig  method that uses it) is to help accessing the tracer in the runtime environment - it is not per instrumentation.

So just to clarify - instrumentations should use an explicitly provided Tracer or one obtained from GlobalTracer. However in SB, Swarm etc, support for resolving the Tracer at the beginning of the app could include using the TracerResolver.

**Comment by pavolloffay** [comment]
> @pavolloffay Not sure where this came from - ther is no binding to tracerresolver in any instrumention. The use of the tracerresolver is simply to obtain the Tracer once per app invocation, so providing runtime specific support (e.g. a SB Bean autoconfig method that uses it) is to help accessing the tracer in the runtime environment - it is not per instrumentation.

By binding, I mean `Tracerresolver.get()`

**Comment by objectiser** [comment]
The framework instrumentations shouldn't use this - only the application or some runtime support (e.g. autoconfig in SB, CDI producer, etc).

**Comment by sjoerdtalsma** [comment]
>The framework instrumentations shouldn't use this - only the application or some runtime support (e.g. autoconfig in SB, CDI producer, etc).

I totally agree with this statement.
Also with this issue. So can I get a volunteer for a PR to add a paragraph to the README as my English isn't as concise as yours? :wink:

**Comment by objectiser** [comment]
Your English is just fine :) - I'm having trouble thinking about the best way to express it, but will create a PR if I get something worth discussing.

**Comment by sjoerdtalsma** [comment]
PR #16 merged into version `0.1.2`.
`TracerResolver.resolveTracer()` becomes `GlobalTracer.get()` if `GlobalTracer.isRegistered() == true`.

**Comment by sjoerdtalsma** [comment]
This has been resolved by #16 and #23.
