### ISSUE TITLE
Enable travis-ci integration.

### ISSUE THREAD

**Issue by sjoerdtalsma** [opentracing-contrib/java-tracerresolver#2]
@bhs Travis CI should be enabled for this project.
The build must be enabled in travis and the following environment variables should be added to the travis-ci project settings (all encrypted except for `GH_USER`):
- `GH_USER`
- `GH_TOKEN`
- `BINTRAY_USER`
- `BINTRAY_KEY`
- `SONATYPE_USER`
- `SONATYPE_PASSWORD`

Alternatively I could do this but that requires admin rights to this repo.

**Comment by bhs** [comment]
![image](https://cloud.githubusercontent.com/assets/2251553/25288075/bec063ae-2678-11e7-84a1-a08c41ce5193.png)

Leaving this open since there's still the travis config stuff. Thanks!

**Comment by sjoerdtalsma** [comment]
I added the environment variables in travis. The project should now build and deploy.
