### ISSUE TITLE
Release (0.1.1?)

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/java-tracerresolver#21]
I would like to ask for a release with OT API 0.30.0

**Comment by sjoerdtalsma** [comment]
Of course I'd be happy to do that for you.
However I think `0.1.0` should work with upgraded opentracing-api out of the box, as there are no assumptions about the tracer.

Please let me know if you wish to make the release nonetheless.

**Comment by pavolloffay** [comment]
unfortunately, it does not work :/ a release would be good.

**Comment by sjoerdtalsma** [comment]
Release `0.1.1` should be on its way...

**Comment by pavolloffay** [comment]
awesome thanks

**Comment by sjoerdtalsma** [comment]
The travis release job stalled (https://travis-ci.org/opentracing-contrib/java-tracerresolver/builds/263137268).
I restarted it manually, hope the release runs ok this time.

I'll have to go now, will check on the status again later. For the moment I'll re-open the issue to make sure I won't forget to check :wink:

**Comment by sjoerdtalsma** [comment]
Ok, build nr. 75 (the release) actually failed on the retry
>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project opentracing-tracerresolver: Failed to deploy artifacts: Could not transfer artifact io.opentracing.contrib:opentracing-tracerresolver:jar:0.1.1 from/to bintray (https://api.bintray.com/maven/opentracing/maven/opentracing-tracerresolver/;publish=1): Failed to transfer file: https://api.bintray.com/maven/opentracing/maven/opentracing-tracerresolver/;publish=1/io/opentracing/contrib/opentracing-tracerresolver/0.1.1/opentracing-tracerresolver-0.1.1.jar. Return code is: 409, ReasonPhrase: Conflict. -> [Help 1]

The good news is that the reason seems to be that version `0.1.1` is already available 😄

**Comment by pavolloffay** [comment]
bintray sometimes returns weird things.

**Comment by sjoerdtalsma** [comment]
Yeah, do we actually _need_ bintray?
I release my own artifacts using the nexus staging plugin + gpg plugin.
